### ISSUE TITLE
String helper library

### ISSUE THREAD

**Issue by cdtweb** [nonamephp/php7-common#34]
## Methods
* `startsWith(string $string, string $prefix, bool $caseSensitive = true): bool` Checks if `$string` starts with `$prefix`. Optionally case-insensitive.
* `endsWith(string $string, string $suffix, bool $caseSensitive = true): bool` Checks if `$string` ends with `$suffix`. Optionally case-insensitive.
* `equals(string $a, string $b, bool $caseSensitive = true): bool` Checks if `$a` is equal to `$b`. Optionally case-insensitive.

**Comment by iamface** [comment]
Submitted pull request with included tests.

**Comment by cdtweb** [comment]
Merged pull request #35
